@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\common\bin\cspybat" "D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\arm\bin\armproc.dll" "D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\arm\bin\armjlink.dll"  %1 --plugin "D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\arm\bin\armbat.dll" --flash_loader "D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\arm\config\flashloader\NXP\FlashNXPLPC512K_7x_8x_Cortex.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "D:\Program Files\IAR Systems\Embedded Workbench 6.0 Evaluation\arm\CONFIG\debugger\NXP\iolpc1788.ddf" "--drv_verify_download" "--semihosting" "--device=LPC1788" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--jlink_reset_strategy=0,0" "--jlink_interface=SWD" "--drv_catch_exceptions=0x000" "--drv_swo_clock_setup=72000000,0,2000000" 


