/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        Bitmap converter for emWin V5.04.
*        Compiled Jan  8 2010, 16:37:17
*        (C) 1998 - 2005 Segger Microcontroller Systeme GmbH
*
**********************************************************************
*
* Source file: 320_Overview_ArrowDown_2
* Dimensions:  4 * 12
* NumColors:   0
*
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned short ac320_Overview_ArrowDown_2[] = {
  0x071F, 0x071F, 0x071F, 0x071F,
  0x071F, 0x071F, 0x071F, 0x071F,
  0x071F, 0x071F, 0x071F, 0x071F,
  0x071F, 0x071F, 0x071F, 0x071F,
  0x071F, 0x071F, 0x071F, 0x071F,
  0x16DC, 0x0000, 0x10A6, 0x071F,
  0x16DC, 0x0000, 0x10A6, 0x071F,
  0x16DC, 0x0000, 0x10A6, 0x071F,
  0x1D4B, 0x0000, 0x0421, 0x1DD1,
  0x1678, 0x0000, 0x0843, 0x0EFD,
  0x071F, 0x110A, 0x15D2, 0x071F,
  0x071F, 0x1678, 0x1678, 0x071F
};

extern GUI_CONST_STORAGE GUI_BITMAP bm320_Overview_ArrowDown_2;

GUI_CONST_STORAGE GUI_BITMAP bm320_Overview_ArrowDown_2 = {
  4, /* XSize */
  12, /* YSize */
  8, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)ac320_Overview_ArrowDown_2,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_BMP555
};

/* *** End of file *** */
